### ISSUE TITLE
使用报错Segmentation fault

### ISSUE THREAD

**Issue by jiuyue52** [shengyanli1982/oxide-wdns#9]
Linux  6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux
DEbian12 内核6.1.0-27-amd64
下载的打包好的二进制文件，不管是我修改后的config还是直接cv示例的配置，都是同样的报错
```
http_server:
  listen_addr: "127.0.0.1:3053"
  timeout: 120

  rate_limit:
    enabled: false
    per_ip_rate: 100
    per_ip_concurrent: 10

dns_resolver:
  upstream:
    enable_dnssec: true
    query_timeout: 30
    resolvers:
      - address: "https://8888.google/dns-query"
        protocol: "doh"
      - address: "https://dns.nextdns.io/dns-query"
        protocol: "doh"

  http_client:
    timeout: 120

    pool:
      idle_timeout: 30
      max_idle_connections: 30

    request:
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
      ip_header_names:
        - "X-Forwarded-For"
        - "X-Real-IP"
        - "CF-Connecting-IP"

  cache:
    enabled: true
    size: 10000

    ttl:
      min: 60
      max: 86400
      negative: 300

  routing:
    enabled: true

    upstream_groups:
      - name: "cn_doh"
        enable_dnssec: false
        query_timeout: 15
        resolvers:
          - address: "https://dns.alidns.com/dns-query"
            protocol: "doh"
          - address: "https://doh.pub/dns-query"
            protocol: "doh"

      - name: "nocn_doh"
        resolvers:
          - address: "https://8888.google/dns-query"
            protocol: "doh"
          - address: "https://dns.nextdns.io/dns-query"
            protocol: "doh"

    rules:
      - match:
          type: url
          url: "https://rules.vlo.cc/aox.txt"
        upstream_group: "__blackhole__"

      - match:
          type: url
          url: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt"
        upstream_group: "cn_doh"

      - match:
          type: url
          url: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt"
        upstream_group: "nocn_doh"

      - match:
          type: url
          url: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt"
        upstream_group: "nocn_doh"


    default_upstream_group: "nocn_doh"

```
